In [27]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array(range(6)).reshape((3,2))
a,b

(array([1, 2, 3]),
 array([[0, 1],
        [2, 3],
        [4, 5]]))

In [28]:
a*b[:,1]

array([ 1,  6, 15])

In [24]:
print(np.sum(b, axis=1))

[1 5 9]


In [14]:
a,b

(array([1, 2, 3]),
 array([[0, 1, 2],
        [3, 4, 5]]))

In [18]:
def sigmoid(z):
    return 1.0/(1.0 + np.exp(-z))

v = np.vectorize(sigmoid)

array([[0.5       , 0.73105858, 0.88079708],
       [0.95257413, 0.98201379, 0.99330715]])